/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devgest;

import datechooser.beans.DateChooserCombo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.event.*; 
import java.awt.*; 
import javax.swing.*; 

/**
 *
 * @author deraa
 */
public class EnregistrerDevoir extends javax.swing.JInternalFrame implements ActionListener {
    private EnregistrerDevoir saveDev;
    Accesseur access = new Accesseur();
    public String selectedProf;
    public String selectedClas;
    public String selectedMat;
    public String selectedSurv;
    public String selectedSalle;

    /**
     * Creates new form EnregistrerDevoir
     */
    public EnregistrerDevoir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date = new datechooser.beans.DateChooserCombo();
        heure = new javax.swing.JTextField();
        prof = new javax.swing.JComboBox<>();
        mat = new javax.swing.JComboBox<>();
        clas = new javax.swing.JComboBox<>();
        AnnulerDevoir = new javax.swing.JButton();
        ValiderDevoir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        surv = new javax.swing.JComboBox<>();
        salle = new javax.swing.JComboBox<>();

        content.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setText("Enregistrer un devoir");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N

        jLabel2.setText("Date :");

        jLabel3.setText("Heure : ");

        jLabel4.setText(" Professeur : ");

        jLabel5.setText("Matière : ");

        jLabel6.setText("Classe : ");

        date.setCalendarBackground(new java.awt.Color(0, 153, 255));
        date.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateOnCommit(evt);
            }
        });

        heure.setText("15:00");

              JComboBox<String> prof = new JComboBox<>();
        // add items to the combo box
        prof.addItem("N0010");
        prof.addItem("N002");
        prof.addItem("N003");
        prof.addItem("N004");
        prof.addItem("N005");
        prof.addItem("N006");
        prof.addItem("N007");
        prof.addItem("N008");
        prof.addItem("N009");
        
        add(prof); 
        // code pour generer automatiquement les élements de la base de données ici
        //prof.setSelectedItem("N0020");
        selectedProf = (String) prof.getSelectedItem();

        JComboBox<String> mat = new JComboBox<>();
        // add items to the combo box
        mat.addItem("ANG1541");
        mat.addItem("COM1501");
        mat.addItem("INF1511");
        mat.addItem("INF1521");
        mat.addItem("INF1522");
        mat.addItem("INF1523");
        mat.addItem("TCC1501");
        mat.addItem("MTH1541");
        mat.addItem("MTH1542");
        selectedMat = (String) mat.getSelectedItem();
        

        JComboBox<String> clas = new JComboBox<>();
        // add items to the combo box
        clas.addItem("L1MIAGE");
        clas.addItem("L2MIAGE");
        clas.addItem("L3MIAGE");
        clas.addItem("L1ABF");
        clas.addItem("L2ABF");
        clas.addItem("L3ABF");
        clas.addItem("L1ADB");
        clas.addItem("L2ADB");
        clas.addItem("L3ADB");
        selectedClas = (String) clas.getSelectedItem();

        AnnulerDevoir.setText("Annuler");
        AnnulerDevoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerDevoirActionPerformed(evt);
            }
        });

        ValiderDevoir.setText("Valider");
        ValiderDevoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderDevoirActionPerformed(evt);
            }
        });

        jLabel7.setText("Code devoir :");

        code.setText("Exemple: D001");
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        jLabel8.setText("Code Surveillant : ");

        jLabel9.setText("Salle : ");

       
        JComboBox<String> surv = new JComboBox<>();
        // add items to the combo box
        surv.addItem("S001");
        surv.addItem("S002");
        surv.addItem("S0003");

        selectedSurv = (String) surv.getSelectedItem();

        JComboBox<String> salle = new JComboBox<>();
        // add items to the combo box
        salle.addItem("SC1");
        salle.addItem("SC2");
        salle.addItem("SC3");
        salle.addItem("SC5");
        salle.addItem("SC6");
        salle.addItem("SC7");
        salle.addItem("SI2");
        salle.addItem("SI4");
        selectedSalle = (String) salle.getSelectedItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AnnulerDevoir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValiderDevoir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(heure)
                            .addComponent(prof, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(code)
                            .addComponent(surv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(clas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7))
                            .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8))
                    .addComponent(surv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnnulerDevoir)
                    .addComponent(ValiderDevoir))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasActionPerformed

    private void ValiderDevoirActionPerformed(java.awt.event.ActionEvent evt) throws NullPointerException{//GEN-FIRST:event_ValiderDevoirActionPerformed
        // TODO add your handling code here:
            Object source = evt.getSource();
           //Object Object test;
            
 
		if(source == ValiderDevoir){
                    /*ValiderDevoir.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) { 
                     System.out.println("Valeur: " + prof.getSelectedItem()); 
                     //prof.getSelectedItem();
    
                      //access.setCodeP(prof.getSelectedItem());
                    
                       /*if (prof.getSelectedIndex() != -1) {                     
                       access.setCodeP(prof.getItemAt(prof.getSelectedIndex()));             
                       }            
                       
                    }
                 }); */
                    
                    access.setCodeD(code.getText());
                   access.setDateD(date.getText());
                    access.setHeureD(heure.getText());
                    access.setCodeM(selectedMat);
                    access.setCodeP(selectedProf);
                    access.setCodeCl(selectedClas);
                    access.setCodeS(selectedSurv);
                    access.setCodeSa(selectedSalle);
                    
                    //access.setCodeP(prof.);
                    
                ModelDevoir modelDev= new ModelDevoir();
             
                    try {
                       boolean x = modelDev.enregistrerDevoir(access.getCodeD(), access.getDateD(), access.getHeureD(),access.getcodeS(),access.getCodeM(), access.getCodeCl(), access.getCodeP(),access.getCodeSa());
                       if (x==true){
                           System.out.println("success");
                       }else System.out.println("echec");
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(EnregistrerDevoir.class.getName()).log(Level.SEVERE, null, ex);
                    }
		} else if(source == AnnulerDevoir){
                 Dash dash = new Dash();
            content.add(dash).setVisible(true);
		}
    }//GEN-LAST:event_ValiderDevoirActionPerformed

                           @Override
                    public void actionPerformed(ActionEvent e) {
                        if(e.getSource()==ValiderDevoir){
                            //System.out.println(prof.getSelectedItem());
                            //test =  prof.getSelectedItem();
                        }
                    }
     
    
    private void dateOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateOnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOnCommit

    private void AnnulerDevoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerDevoirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnnulerDevoirActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerDevoir;
    private javax.swing.JButton ValiderDevoir;
    private javax.swing.JComboBox<String> clas;
    private javax.swing.JTextField code;
    private javax.swing.JPanel content;
    private datechooser.beans.DateChooserCombo date;
    private javax.swing.JTextField heure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mat;
    private javax.swing.JComboBox<String> prof;
    private javax.swing.JComboBox<String> salle;
    private javax.swing.JComboBox<String> surv;
    // End of variables declaration//GEN-END:variables

  /*  public DateChooserCombo getDate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return date;
    }
    public JTextField getHeure() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return heure;
    }
    public JComboBox getMat() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return mat;
    }
    public JComboBox getClas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return clas;
    }
    public JComboBox getProf() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return prof;
    }
    public JTextField getCode() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return code;
    }*/
}
